<?php

namespace App\Enums\Backoffice;

enum ApprovalType: string
{
    case REVERSAL = 'REVERSAL';
    case ACCOUNT_CLOSURE = 'ACCOUNT_CLOSURE';
    case LARGE_CASH_OUT = 'LARGE_CASH_OUT';
    case BACKOFFICE_USER_PRIVILEGE_ELEVATION = 'BACKOFFICE_USER_PRIVILEGE_ELEVATION';
    case FEE_RULE_CHANGE = 'FEE_RULE_CHANGE';
    case COMMISSION_RULE_CHANGE = 'COMMISSION_RULE_CHANGE';
    case CONTROL_THRESHOLD_CHANGE = 'CONTROL_THRESHOLD_CHANGE';
    case LIMIT_PROFILE_CHANGE = 'LIMIT_PROFILE_CHANGE';
    case SERVICE_PROVIDER_CHANGE = 'SERVICE_PROVIDER_CHANGE';
    case BILL_PROVIDER_SETTLEMENT = 'BILL_PROVIDER_SETTLEMENT';
    case PLATFORM_REVENUE_WITHDRAWAL = 'PLATFORM_REVENUE_WITHDRAWAL';
    case PLATFORM_LIQUIDITY_TOP_UP = 'PLATFORM_LIQUIDITY_TOP_UP';
    case RECONCILIATION_ADJUSTMENT = 'RECONCILIATION_ADJUSTMENT';
    case AGENT_FUND_IN = 'AGENT_FUND_IN';
    case AGENT_FUND_OUT = 'AGENT_FUND_OUT';
}
