<?php

namespace App\Enums\Backoffice;

enum TransactionType: string
{
    case CASH_IN = 'CASH_IN';
    case PAYMENT = 'PAYMENT';
    case CASH_OUT = 'CASH_OUT';
    case CARD_SALE = 'CARD_SALE';
    case AGENT_FUND_IN = 'AGENT_FUND_IN';
    case AGENT_FUND_OUT = 'AGENT_FUND_OUT';
    case FEE_COLLECTION = 'FEE_COLLECTION';
    case COMMISSION_PAYOUT = 'COMMISSION_PAYOUT';
    case REVERSAL = 'REVERSAL';
    case P2P_TRANSFER = 'P2P_TRANSFER';
    case MERCHANT_TO_MERCHANT = 'MERCHANT_TO_MERCHANT';
    case PAYMENT_REQUEST = 'PAYMENT_REQUEST';
    case SERVICE_PAYMENT = 'SERVICE_PAYMENT';
    case CARD_REPLACEMENT = 'CARD_REPLACEMENT';
    case BILL_PROVIDER_SETTLEMENT = 'BILL_PROVIDER_SETTLEMENT';
    case PLATFORM_REVENUE_WITHDRAWAL = 'PLATFORM_REVENUE_WITHDRAWAL';
    case PLATFORM_LIQUIDITY_TOP_UP = 'PLATFORM_LIQUIDITY_TOP_UP';
}
